title = "jasonwhite"
description = "Ceci n'est pas un blog."

# The URL the site will be built for
base_url = "https://jasonwhite.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "jason"

taxonomies = [
    {name = "tags", paginate_by = 5, rss = true}
]

[extra]
analytics_id = "UA-168895742-1"

nav_links = [
    {url = "$BASE_URL/tags", name = "Tags"},
    {url = "https://github.com/jasonwhite", name = "Github"},
]

# Slim theme configuration
slim_footer = "Copyright &copy; 2021 Jason White"
